# Generated by Django 3.2.20 on 2023-11-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image_url',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
