# Generated by Django 3.2.20 on 2023-11-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlist_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=228, null=True),
        ),
    ]
